.PHONY: binaries

binaries:
	rm -rf binaries
	mkdir -p binaries/node_modules
	cp ../built_pkg/oak-linux binaries/oak
	cp -r ../node_modules/better-sqlite3 binaries/node_modules
	cp -r ../node_modules/bindings binaries/node_modules
	cp -r ../node_modules/file-uri-to-path binaries/node_modules
	cp -r ../node_modules/integer binaries/node_modules
