FROM python:3.8.1-alpine3.11

RUN apk --no-cache add  \
      build-base \
      python3-dev \
      zlib-dev \
      jpeg-dev \
      freetype-dev \
      lcms2-dev \
      openjpeg-dev \
      tiff-dev \
      tk-dev \
      tcl-dev \
      harfbuzz-dev \
      fribidi-dev

RUN python -m pip install Pillow
